# -*- coding: utf-8 -*-
"""Static

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LhVDHfIXRxsluqcjdTV1z1ZBIOzMpOce

# Importing Necessary Libraries and Drive mounting
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('tableau-colorblind10')
# %matplotlib inline
from google.colab import drive
drive.mount('/content/drive',force_remount=False)

"""# Reading Data"""

import pandas as pd
data = pd.read_csv('/content/drive/My Drive/static.csv')
#len(data)

"""# **Data Cleaning**

# Selecting necessary columns and obtaining null percentage for each Column
"""

df = data[['DR_NO','Date Rptd','DATE OCC','TIME OCC','AREA NAME', 'Crm Cd Desc', 'Vict Age', 'Vict Sex','Vict Descent','LAT','LON']]
#display(df)
(df.isnull().sum()).sort_values(ascending=False) / df.shape[0]

df.isna().any()

"""# Dropping Null valued rows

"""

# removing blank values for 'Vict Descent', 'Vict Sex'
df.dropna(subset=['Vict Descent', 'Vict Sex'],inplace=True)

#Verifying for null valued rows
df.isna().any()

# checking the statistical data for each column
df.describe()
df.count()

# removing the values ​​below one for the "Vict Age" column
df.drop(df[df['Vict Age'] < 1].index, axis=0, inplace=True)
df.count()